version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: api.dockerfile
    image: interview/api:latest
    container_name: interview_api
    ports: 
      - 8888:8888
  dummy:
    image: alpine/curl:3.14
    container_name: dummy
    command: 
      - /bin/sh
      - -c
      - |
        curl -X 'POST' 'http://api:8888/users/' -H 'accept: application/json' -H 'Content-Type: application/json' -d '{"email": "bilbo@baggins.com", "password": "whyshouldnti"}'
        curl -X 'POST' 'http://api:8888/users/1/items/' -H 'accept: application/json' -H 'Content-Type: application/json' -d '{"title": "Sting","description": "\"I will give you a name\", he said to it, \"and I shall call you Sting.\""}'
        curl -X 'POST' 'http://api:8888/users/1/items/' -H 'accept: application/json' -H 'Content-Type: application/json' -d '{"title": "The One Ring","description": "To rule them all."}'
        curl -X 'POST' 'http://api:8888/users/1/items/' -H 'accept: application/json' -H 'Content-Type: application/json' -d '{"title": "Halfling Leaf","description": "Your love for the halflings leaf has slowed your mind."}'

    depends_on:
      - api
    links:
      - api

